# Project information
site_name: The ACM Manipal Blog
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Blogs: Blogs.md
  - WebDev: WebDev.md
  - AppDev: AppDev.md
  - ML&AI: MLAI.md
  - Coding: Coding.md
  - CommunityService: Community Service.md
  - Research: Research.md
  - Gallery: ACM Gallery.md


site_author: Daksh Dadhania
site_description: >-
  The ACM Manipal Blog
  Keep calm and write code.
  We’ll be putting up helpful and interesting articles written by our members.

# Repository
repo_name: github.com/acmmanipal
repo_url: https://github.com/acmmanipal

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/acmmanipal
    - icon: fontawesome/brands/medium
      link: https://medium.com/the-acm-manipal-blog
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/acm-manipal/mycompany/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/acm_manipal/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/acmmanipal"  target="_blank" rel="noopener">ACM Manipal</a>